# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23d1a9b2da5c562dd12ea3894acd23d919fb753889c9e6e655e9ea072a75ef7fd9ede658733243c069ecde409218ad7ad00726d9ed83ff1abd7baae81ba96264

test:
  secret_key_base: 8edd3b41f2e2341dfb741d82b5cd15be7d4c019a66479dc64ade35f319f11bdfadf072041877a486c440b06d22b22690b41637aa0158cf9ee8be91c6e2a6ce6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
