mysql:
 hostname: localhost
 port: 3306
 socket: /tmp/mysql.sock
 username: user
 password: password
 database: mysql-db

destination:
 postgres:
  hostname: localhost
  port: 5432
  username: user
  password: password
  database: pg-db
