development:
  adapter: postgresql
  host: localhost
  port: 5432
  username: daveoleson
  password: 
  database: myapp_development
 
test:
  adapter: postgresql
  host: localhost
  port: 5432
  username: daveoleson
  password: 
  database: myapp_test